-- Drop table if it exists
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM user_tables WHERE table_name = 'EMPLOYEES';
    IF table_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES';
    END IF;
END;
/

-- Create the table
CREATE TABLE EMPLOYEES (
    id NUMBER generated by default as identity,
    name VARCHAR2(50),
    age NUMBER
);

-- Insert 10 sample records
INSERT INTO EMPLOYEES (name, age) VALUES ('Alice', 30);
-- Repeat similar INSERT statements for other records...

-- Output records
SET SERVEROUTPUT ON
BEGIN
    FOR rec IN (SELECT * FROM EMPLOYEES) LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || rec.id || ', Name: ' || rec.name || ', Age: ' || rec.age);
    END LOOP;
END;
/
